ret_p_hyperparams:
  drop_double_returns: False
  min_joint_baskets: [5] # [0, 5, 10, 15]
  weights: ["sqrt_w"] # [False, "lin_w", "sqrt_w"]
  top_freq_arts: [5] # [False, 3, 5, 10, "var_5"]
random_state: 42
ret_col: 'returnShipment'
ordnr_col: 'basketID'
artnr_col: 'itemID'
budgets: 10
coldict:
  cat_pass: ['DAY_ORDER', 'DAY_RECEIVED', 'WE_DELIVERY', 'ACC_OLD_SYS', "color", "size"]
  cat_catboost: ["manufacturerID", "salutation", "state", 'item_color_cat', 'item_size_cat'] # double: one normal + one catboost col; seperate for arguments -> ["manufacturerID", "salutation", "state"] + ['item_color_cat', 'item_size_cat']
  cont_pass: ['discount', 'basket_price', 'basketNArts', 'TIME_DELIVERY', , 'ACC_AGE_ORDER']
  retp_imp: ['min_5_top_5_sqrt_w_lift', 'min_5_top_5_sqrt_w_conf']
  cont_impute: ['USER_AGE_ORDER']